### ISSUE TITLE
Yt-dlp auto update

### ISSUE THREAD

**Issue by Gandulf78** [tuxpeople/docker-podsync#53]
Hi. 
Thank you for this image. It is working great on my ARMv7 NAS. I've noticed that the self-update option for yt-dlp is not working though. 

time="2022-05-10T20:19:31Z" level=info msg="updating youtube-dl"
time="2022-05-10T20:19:49Z" level=info msg="[debug] Command-line config: ['--update', '--verbose']\n[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8\n[debug] yt-dlp version 2021.11.10.1\n[debug] Python version 3.9.7 (CPython 32bit) - Linux-4.14.22-armada-18.09.3-armv7l-with\n[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1\n[debug] Optional libraries: sqlite\n[debug] Proxy map: {}\nLatest version: 2022.03.08, Current version: 2021.11.10.1\nERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball; Use that to update\n"

Is there something to be done about that?
Thanks.

**Comment by tuxpeople** [comment]
First and foremost: Sorry for the delay. I'm completely buried with work and completely missed your issue.

Right now, it is not possible to use the `yt-dlp` integrated update routine. I completely missed that tbh. I'll take a look at this, as soon as I can. But I can't promise anything right now.

**Comment by tuxpeople** [comment]
@Gandulf78 would you mind to try and test this image? 

`ghcr.io/tuxpeople/podsync:pr55-v2.4.2`

**Comment by Gandulf78** [comment]
Thank you. I tried it but it cycles failing:

time="2022-05-25T19:42:21Z" level=info msg="running podsync" commit=none date=unknown version=dev
time="2022-05-25T19:42:21Z" level=fatal msg="youtube-dl error" error="could not find youtube-dl: failed to execute youtube-dl: exit status 127"
time="2022-05-25T19:43:29Z" level=info msg="\n _______  _______  ______   _______           _        _______ \n(  ____ )(  ___  )(  __  \\ (  ____ \\|\\     /|( (    /|(  ____ \\\n| (    )|| (   ) || (  \\  )| (    \\/( \\   / )|  \\  ( || (    \\/\n| (____)|| |   | || |   ) || (_____  \\ (_) / |   \\ | || |      \n|  _____)| |   | || |   | |(_____  )  \\   /  | (\\ \\) || |      \n| (      | |   | || |   ) |      ) |   ) (   | | \\   || |      \n| )      | (___) || (__/  )/\\____) |   | |   | )  \\  || (____/\\\n|/       (_______)(______/ \\_______)   \\_/   |/    )_)(_______/\n"
time="2022-05-25T19:43:29Z" level=info msg="running podsync" commit=none date=unknown version=dev
time="2022-05-25T19:43:30Z" level=fatal msg="youtube-dl error" error="could not find youtube-dl: failed to execute youtube-dl: exit status 127"
time="2022-05-25T19:44:38Z" level=info msg="\n _______  _______  ______   _______           _        _______ \n(  ____ )(  ___  )(  __  \\ (  ____ \\|\\     /|( (    /|(  ____ \\\n| (    )|| (   ) || (  \\  )| (    \\/( \\   / )|  \\  ( || (    \\/\n| (____)|| |   | || |   ) || (_____  \\ (_) / |   \\ | || |      \n|  _____)| |   | || |   | |(_____  )  \\   /  | (\\ \\) || |      \n| (      | |   | || |   ) |      ) |   ) (   | | \\   || |      \n| )      | (___) || (__/  )/\\____) |   | |   | )  \\  || (____/\\\n|/       (_______)(______/ \\_______)   \\_/   |/    )_)(_______/\n"
time="2022-05-25T19:44:38Z" level=info msg="running podsync" commit=none date=unknown version=dev
time="2022-05-25T19:44:38Z" level=fatal msg="youtube-dl error" error="could not find youtube-dl: failed to execute youtube-dl: exit status 127"

**Comment by tuxpeople** [comment]
@Gandulf78 My bad, sorry. Please try again (please ensure you re-download the image again). Works for me now:

```
docker run \
    -p 8080:8080 \
    -v $(pwd)/config.toml:/app/config.toml:ro \
    ghcr.io/tuxpeople/podsync:pr55-v2.4.2


Unable to find image 'ghcr.io/tuxpeople/podsync:pr55-v2.4.2' locally
pr55-v2.4.2: Pulling from tuxpeople/podsync
b3c136eddcbf: Already exists
fdfc27729fdf: Pull complete
b74b2a75e8c0: Pull complete
609e8c5cbed0: Pull complete
Digest: sha256:5f9443078788c5eacef508d72f73453fbfeb6f68a0ea3eb78f50849c9f04cf9f
Status: Downloaded newer image for ghcr.io/tuxpeople/podsync:pr55-v2.4.2
time="2022-05-27T09:45:54Z" level=info msg="\n _______  _______  ______   _______           _        _______ \n(  ____ )(  ___  )(  __  \\ (  ____ \\|\\     /|( (    /|(  ____ \\\n| (    )|| (   ) || (  \\  )| (    \\/( \\   / )|  \\  ( || (    \\/\n| (____)|| |   | || |   ) || (_____  \\ (_) / |   \\ | || |      \n|  _____)| |   | || |   | |(_____  )  \\   /  | (\\ \\) || |      \n| (      | |   | || |   ) |      ) |   ) (   | | \\   || |      \n| )      | (___) || (__/  )/\\____) |   | |   | )  \\  || (____/\\\n|/       (_______)(______/ \\_______)   \\_/   |/    )_)(_______/\n"
time="2022-05-27T09:45:54Z" level=info msg="running podsync" commit=none date=unknown version=dev
time="2022-05-27T09:45:54Z" level=info msg="using youtube-dl 2022.05.18\n"
time="2022-05-27T09:45:54Z" level=info msg="found ffmpeg: ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers\nbuilt with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219\nconfiguration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug\nlibavutil      57. 17.100 / 57. 17.100\nlibavcodec     59. 18.100 / 59. 18.100\nlibavformat    59. 16.100 / 59. 16.100\nlibavdevice    59.  4.100 / 59.  4.100\nlibavfilter     8. 24.100 /  8. 24.100\nlibswscale      6.  4.100 /  6.  4.100\nlibswresample   4.  3.100 /  4.  3.100\nlibpostproc    56.  3.100 / 56.  3.100\n"
time="2022-05-27T09:45:54Z" level=info msg="updating youtube-dl"
time="2022-05-27T09:45:55Z" level=info msg="[debug] Command-line config: ['--update', '--verbose']\n[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)\n[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)\n[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.10.104-linuxkit-aarch64-with\n[debug] Checking exe version: ffprobe -bsfs\n[debug] Checking exe version: ffmpeg -bsfs\n[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1\n[debug] Optional libraries: sqlite3-2.6.0\n[debug] Proxy map: {}\nLatest version: 2022.05.18, Current version: 2022.05.18\nyt-dlp is up to date (2022.05.18)\n"
time="2022-05-27T09:45:55Z" level=info msg="opening database \"db\""
time="2022-05-27T09:45:55Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-05-27T09:45:55Z" level=info msg="-> updating https://www.youtube.com/channel/UCdsHxxxxxxxxxxxxxxxxxxxQa457w" feed_id=yyyyyyyyy format=audio quality=high
time="2022-05-27T09:45:55Z" level=info msg="running listener at :8080"
time="2022-05-27T09:45:55Z" level=info msg="downloading episodes" page_size=5
time="2022-05-27T09:45:55Z" level=info msg="download count: 5"
time="2022-05-27T09:45:55Z" level=info msg="! downloading episode https://youtube.com/watch?v=DMxxxxxxII" episode_id= DMxxxxxxII index=0
time="2022-05-27T09:46:00Z" level=info msg="creating file: /data/yyyyyyyyy/DMxxxxxxII.mp3" name=yyyyyyyyy/DMxxxxxxII.mp3
```

**Comment by Gandulf78** [comment]
Thanks. It is working.
I am facing another issue though. I don't know yet if it is related to this patched version or if it is the same with the released one.
I notice an over memory consumption of podsync. See below.

![image](https://user-images.githubusercontent.com/44120190/170814780-a1d6ac76-7a2c-4d4d-bb8a-93b4c499147a.jpeg)

**Comment by tuxpeople** [comment]
@Gandulf78 thanks for digging into this. 

Looks like we have an issue then. If the problem is in podsync itself, I can't help. And the podsync author will probably not help with a 3rd party container, I'd say.

As I'm compiling it myself, I can check if upstream changed something there which I can do as well here. Or I can try to download his Binaries, but this would be an extra effort.

Feel free to open an issue for this here, so I can try to do one of the above mentioned things. But I would need you to test it, I do not have an ARM NAS available. All ARM things I have are arm64 things.

**Comment by Gandulf78** [comment]
Thanks. With your arm64 config, do you have memory issues on your side?
